[2022-10-17 11:03:35,043] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dbt.dbt_snapshot scheduled__2022-10-14T00:00:00+00:00 [queued]>
[2022-10-17 11:03:35,056] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dbt.dbt_snapshot scheduled__2022-10-14T00:00:00+00:00 [queued]>
[2022-10-17 11:03:35,056] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-17 11:03:35,056] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-17 11:03:35,056] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-17 11:03:35,073] {taskinstance.py:1377} INFO - Executing <Task(DbtSnapshotOperator): dbt_snapshot> on 2022-10-14 00:00:00+00:00
[2022-10-17 11:03:35,076] {standard_task_runner.py:52} INFO - Started process 262969 to run task
[2022-10-17 11:03:35,080] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dbt', 'dbt_snapshot', 'scheduled__2022-10-14T00:00:00+00:00', '--job-id', '118', '--raw', '--subdir', 'DAGS_FOLDER/dbt_airflow.py', '--cfg-path', '/tmp/tmp34s3vdqg', '--error-file', '/tmp/tmpt5f3a0rf']
[2022-10-17 11:03:35,081] {standard_task_runner.py:80} INFO - Job 118: Subtask dbt_snapshot
[2022-10-17 11:03:35,131] {task_command.py:370} INFO - Running <TaskInstance: dbt.dbt_snapshot scheduled__2022-10-14T00:00:00+00:00 [running]> on host ubuntu
[2022-10-17 11:03:35,176] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dbt
AIRFLOW_CTX_TASK_ID=dbt_snapshot
AIRFLOW_CTX_EXECUTION_DATE=2022-10-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-14T00:00:00+00:00
[2022-10-17 11:03:35,176] {dbt_hook.py:117} INFO - dbt snapshot
[2022-10-17 11:03:35,181] {dbt_hook.py:126} INFO - Output:
[2022-10-17 11:03:37,857] {dbt_hook.py:130} INFO - 18:03:37  Running with dbt=1.1.0
[2022-10-17 11:03:37,944] {dbt_hook.py:130} INFO - 18:03:37  Found 6 models, 5 tests, 6 snapshots, 0 analyses, 400 macros, 0 operations, 7 seed files, 2 sources, 0 exposures, 0 metrics
[2022-10-17 11:03:37,946] {dbt_hook.py:130} INFO - 18:03:37
[2022-10-17 11:03:41,774] {dbt_hook.py:130} INFO - 18:03:41  Concurrency: 2 threads (target='dev')
[2022-10-17 11:03:41,775] {dbt_hook.py:130} INFO - 18:03:41
[2022-10-17 11:03:41,782] {dbt_hook.py:130} INFO - 18:03:41  1 of 6 START snapshot DBT_HAMS71.Core_Accounts ................................. [RUN]
[2022-10-17 11:03:41,784] {dbt_hook.py:130} INFO - 18:03:41  2 of 6 START snapshot DBT_HAMS71.Core_Address .................................. [RUN]
[2022-10-17 11:03:46,813] {dbt_hook.py:130} INFO - 18:03:46  2 of 6 ERROR snapshotting DBT_HAMS71.Core_Address .............................. [[31mERROR[0m in 5.03s]
[2022-10-17 11:03:46,815] {dbt_hook.py:130} INFO - 18:03:46  3 of 6 START snapshot DBT_HAMS71.Core_Bank ..................................... [RUN]
[2022-10-17 11:03:46,923] {dbt_hook.py:130} INFO - 18:03:46  1 of 6 OK snapshotted DBT_HAMS71.Core_Accounts ................................. [[32mSUCCESS 1[0m in 5.14s]
[2022-10-17 11:03:46,925] {dbt_hook.py:130} INFO - 18:03:46  4 of 6 START snapshot DBT_HAMS71.Core_Branch ................................... [RUN]
[2022-10-17 11:03:51,574] {dbt_hook.py:130} INFO - 18:03:51  4 of 6 OK snapshotted DBT_HAMS71.Core_Branch ................................... [[32mSUCCESS 1[0m in 4.65s]
[2022-10-17 11:03:51,575] {dbt_hook.py:130} INFO - 18:03:51  5 of 6 START snapshot DBT_HAMS71.Core_Contact .................................. [RUN]
[2022-10-17 11:03:52,193] {dbt_hook.py:130} INFO - 18:03:52  3 of 6 OK snapshotted DBT_HAMS71.Core_Bank ..................................... [[32mSUCCESS 1[0m in 5.38s]
[2022-10-17 11:03:57,184] {dbt_hook.py:130} INFO - 18:03:57  5 of 6 ERROR snapshotting DBT_HAMS71.Core_Contact .............................. [[31mERROR[0m in 5.61s]
[2022-10-17 11:03:57,186] {dbt_hook.py:130} INFO - 18:03:57  6 of 6 SKIP relation DBT_HAMS71.Core_Contact_Account_Branch .................... [[33mSKIP[0m]
[2022-10-17 11:03:57,189] {dbt_hook.py:130} INFO - 18:03:57
[2022-10-17 11:03:57,189] {dbt_hook.py:130} INFO - 18:03:57  Finished running 6 snapshots in 19.24s.
[2022-10-17 11:03:57,200] {dbt_hook.py:130} INFO - 18:03:57
[2022-10-17 11:03:57,201] {dbt_hook.py:130} INFO - 18:03:57  [31mCompleted with 2 errors and 0 warnings:[0m
[2022-10-17 11:03:57,201] {dbt_hook.py:130} INFO - 18:03:57
[2022-10-17 11:03:57,201] {dbt_hook.py:130} INFO - 18:03:57  [33mDatabase Error in snapshot Core_Address (snapshots/Core_Address.sql)[0m
[2022-10-17 11:03:57,202] {dbt_hook.py:130} INFO - 18:03:57    100090 (42P18): Duplicate row detected during DML action
[2022-10-17 11:03:57,202] {dbt_hook.py:130} INFO - 18:03:57    Row Values: ["fb89705ae6d743bf1e848c206e16a1d7", "727", 95, "2660 Summit Alley", "92b3ab239bf5a079b6b0430976403097", 1665696227848000000, 1665696227848000000, NULL]
[2022-10-17 11:03:57,202] {dbt_hook.py:130} INFO - 18:03:57    compiled SQL at target/run/dbt_project/snapshots/Core_Address.sql
[2022-10-17 11:03:57,203] {dbt_hook.py:130} INFO - 18:03:57
[2022-10-17 11:03:57,203] {dbt_hook.py:130} INFO - 18:03:57  [33mDatabase Error in snapshot Core_Contact (snapshots/Core_Contact.sql)[0m
[2022-10-17 11:03:57,203] {dbt_hook.py:130} INFO - 18:03:57    100090 (42P18): Duplicate row detected during DML action
[2022-10-17 11:03:57,204] {dbt_hook.py:130} INFO - 18:03:57    Row Values: ["364a1d85b9e86f5b04f03f2248246b4d", 6077, "Limited Liability", "Fax", "Nader Group", "325", "Administrative Officer", "Genovera Klawi", "Research and Development", "3/20/1961", "83875552", "Married", "3", "43406-0099", "522", "55a7144ac633add4eeb8aef0964876e1", 1665696233044000000, 1665696233044000000, NULL]
[2022-10-17 11:03:57,204] {dbt_hook.py:130} INFO - 18:03:57    compiled SQL at target/run/dbt_project/snapshots/Core_Contact.sql
[2022-10-17 11:03:57,204] {dbt_hook.py:130} INFO - 18:03:57
[2022-10-17 11:03:57,205] {dbt_hook.py:130} INFO - 18:03:57  Done. PASS=3 WARN=0 ERROR=2 SKIP=1 TOTAL=6
[2022-10-17 11:03:58,639] {dbt_hook.py:132} INFO - Command exited with return code 1
[2022-10-17 11:03:58,648] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/airflow/airflow_env/lib/python3.8/site-packages/airflow_dbt/operators/dbt_operator.py", line 126, in execute
    self.create_hook().run_cli('snapshot')
  File "/home/ubuntu/airflow/airflow_env/lib/python3.8/site-packages/airflow_dbt/hooks/dbt_hook.py", line 138, in run_cli
    raise AirflowException("dbt command failed")
airflow.exceptions.AirflowException: dbt command failed
[2022-10-17 11:03:58,651] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dbt, task_id=dbt_snapshot, execution_date=20221014T000000, start_date=20221017T180335, end_date=20221017T180358
[2022-10-17 11:03:58,661] {standard_task_runner.py:92} ERROR - Failed to execute job 118 for task dbt_snapshot (dbt command failed; 262969)
[2022-10-17 11:03:58,700] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-17 11:03:58,719] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
