[2022-10-13 11:13:12,162] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dbt.dbt_deps scheduled__2022-10-11T00:00:00+00:00 [queued]>
[2022-10-13 11:13:12,187] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dbt.dbt_deps scheduled__2022-10-11T00:00:00+00:00 [queued]>
[2022-10-13 11:13:12,187] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-13 11:13:12,188] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-13 11:13:12,188] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-13 11:13:12,233] {taskinstance.py:1377} INFO - Executing <Task(DbtDepsOperator): dbt_deps> on 2022-10-11 00:00:00+00:00
[2022-10-13 11:13:12,237] {standard_task_runner.py:52} INFO - Started process 225306 to run task
[2022-10-13 11:13:12,258] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dbt', 'dbt_deps', 'scheduled__2022-10-11T00:00:00+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/dbt_airflow.py', '--cfg-path', '/tmp/tmp13wtvgj3', '--error-file', '/tmp/tmpa4j2iaag']
[2022-10-13 11:13:12,259] {standard_task_runner.py:80} INFO - Job 59: Subtask dbt_deps
[2022-10-13 11:13:12,360] {task_command.py:370} INFO - Running <TaskInstance: dbt.dbt_deps scheduled__2022-10-11T00:00:00+00:00 [running]> on host ubuntu
[2022-10-13 11:13:12,497] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dbt
AIRFLOW_CTX_TASK_ID=dbt_deps
AIRFLOW_CTX_EXECUTION_DATE=2022-10-11T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-11T00:00:00+00:00
[2022-10-13 11:13:12,499] {dbt_hook.py:117} INFO - dbt deps
[2022-10-13 11:13:12,522] {dbt_hook.py:126} INFO - Output:
[2022-10-13 11:13:17,499] {dbt_hook.py:130} INFO - 18:13:17  Running with dbt=1.1.0
[2022-10-13 11:13:17,563] {dbt_hook.py:130} INFO - 18:13:17  Warning: No packages were found in packages.yml
[2022-10-13 11:13:17,571] {dbt_hook.py:130} INFO - 18:13:17  Error sending message, disabling tracking
[2022-10-13 11:13:17,686] {dbt_hook.py:132} INFO - Command exited with return code 0
[2022-10-13 11:13:17,696] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dbt, task_id=dbt_deps, execution_date=20221011T000000, start_date=20221013T181312, end_date=20221013T181317
[2022-10-13 11:13:17,742] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-13 11:13:17,763] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
