[2022-10-11 11:01:13,972] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dbt.dbt_snapshot scheduled__2022-10-10T00:00:00+00:00 [queued]>
[2022-10-11 11:01:13,978] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dbt.dbt_snapshot scheduled__2022-10-10T00:00:00+00:00 [queued]>
[2022-10-11 11:01:13,978] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-11 11:01:13,979] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-11 11:01:13,979] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-11 11:01:13,990] {taskinstance.py:1377} INFO - Executing <Task(DbtSnapshotOperator): dbt_snapshot> on 2022-10-10 00:00:00+00:00
[2022-10-11 11:01:13,994] {standard_task_runner.py:52} INFO - Started process 201872 to run task
[2022-10-11 11:01:14,010] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dbt', 'dbt_snapshot', 'scheduled__2022-10-10T00:00:00+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/dbt_airflow.py', '--cfg-path', '/tmp/tmpxcmjd19d', '--error-file', '/tmp/tmpy9xn1gps']
[2022-10-11 11:01:14,014] {standard_task_runner.py:80} INFO - Job 53: Subtask dbt_snapshot
[2022-10-11 11:01:14,085] {task_command.py:370} INFO - Running <TaskInstance: dbt.dbt_snapshot scheduled__2022-10-10T00:00:00+00:00 [running]> on host ubuntu
[2022-10-11 11:01:14,153] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dbt
AIRFLOW_CTX_TASK_ID=dbt_snapshot
AIRFLOW_CTX_EXECUTION_DATE=2022-10-10T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-10T00:00:00+00:00
[2022-10-11 11:01:14,153] {dbt_hook.py:117} INFO - dbt snapshot
[2022-10-11 11:01:14,159] {dbt_hook.py:126} INFO - Output:
[2022-10-11 11:01:17,090] {dbt_hook.py:130} INFO - 18:01:17  Running with dbt=1.1.0
[2022-10-11 11:01:17,193] {dbt_hook.py:130} INFO - 18:01:17  Found 6 models, 5 tests, 6 snapshots, 0 analyses, 400 macros, 0 operations, 7 seed files, 2 sources, 0 exposures, 0 metrics
[2022-10-11 11:01:17,196] {dbt_hook.py:130} INFO - 18:01:17
[2022-10-11 11:01:20,471] {dbt_hook.py:130} INFO - 18:01:20  Concurrency: 2 threads (target='dev')
[2022-10-11 11:01:20,471] {dbt_hook.py:130} INFO - 18:01:20
[2022-10-11 11:01:20,479] {dbt_hook.py:130} INFO - 18:01:20  1 of 6 START snapshot DBT_HAMS71.Core_Accounts ................................. [RUN]
[2022-10-11 11:01:20,483] {dbt_hook.py:130} INFO - 18:01:20  2 of 6 START snapshot DBT_HAMS71.Core_Address .................................. [RUN]
[2022-10-11 11:01:26,260] {dbt_hook.py:130} INFO - 18:01:26  2 of 6 ERROR snapshotting DBT_HAMS71.Core_Address .............................. [[31mERROR[0m in 5.77s]
[2022-10-11 11:01:26,261] {dbt_hook.py:130} INFO - 18:01:26  3 of 6 START snapshot DBT_HAMS71.Core_Bank ..................................... [RUN]
[2022-10-11 11:01:26,430] {dbt_hook.py:130} INFO - 18:01:26  1 of 6 OK snapshotted DBT_HAMS71.Core_Accounts ................................. [[32mSUCCESS 1[0m in 5.95s]
[2022-10-11 11:01:26,431] {dbt_hook.py:130} INFO - 18:01:26  4 of 6 START snapshot DBT_HAMS71.Core_Branch ................................... [RUN]
[2022-10-11 11:01:31,732] {dbt_hook.py:130} INFO - 18:01:31  3 of 6 OK snapshotted DBT_HAMS71.Core_Bank ..................................... [[32mSUCCESS 1[0m in 5.47s]
[2022-10-11 11:01:31,735] {dbt_hook.py:130} INFO - 18:01:31  5 of 6 START snapshot DBT_HAMS71.Core_Contact .................................. [RUN]
[2022-10-11 11:01:34,957] {dbt_hook.py:130} INFO - 18:01:34  4 of 6 OK snapshotted DBT_HAMS71.Core_Branch ................................... [[32mSUCCESS 1[0m in 8.52s]
[2022-10-11 11:01:37,833] {dbt_hook.py:130} INFO - 18:01:37  5 of 6 ERROR snapshotting DBT_HAMS71.Core_Contact .............................. [[31mERROR[0m in 6.10s]
[2022-10-11 11:01:37,834] {dbt_hook.py:130} INFO - 18:01:37  6 of 6 SKIP relation DBT_HAMS71.Core_Contact_Account_Branch .................... [[33mSKIP[0m]
[2022-10-11 11:01:37,839] {dbt_hook.py:130} INFO - 18:01:37
[2022-10-11 11:01:37,839] {dbt_hook.py:130} INFO - 18:01:37  Finished running 6 snapshots in 20.64s.
[2022-10-11 11:01:37,854] {dbt_hook.py:130} INFO - 18:01:37
[2022-10-11 11:01:37,855] {dbt_hook.py:130} INFO - 18:01:37  [31mCompleted with 2 errors and 0 warnings:[0m
[2022-10-11 11:01:37,856] {dbt_hook.py:130} INFO - 18:01:37
[2022-10-11 11:01:37,857] {dbt_hook.py:130} INFO - 18:01:37  [33mDatabase Error in snapshot Core_Address (snapshots/Core_Address.sql)[0m
[2022-10-11 11:01:37,858] {dbt_hook.py:130} INFO - 18:01:37    100090 (42P18): Duplicate row detected during DML action
[2022-10-11 11:01:37,859] {dbt_hook.py:130} INFO - 18:01:37    Row Values: ["fb89705ae6d743bf1e848c206e16a1d7", "727", 95, "2660 Summit Alley", "4b373a9c844d3e2b16392582a2016ae6", 1665399943377000000, 1665399943377000000, NULL]
[2022-10-11 11:01:37,860] {dbt_hook.py:130} INFO - 18:01:37    compiled SQL at target/run/dbt_project/snapshots/Core_Address.sql
[2022-10-11 11:01:37,861] {dbt_hook.py:130} INFO - 18:01:37
[2022-10-11 11:01:37,862] {dbt_hook.py:130} INFO - 18:01:37  [33mDatabase Error in snapshot Core_Contact (snapshots/Core_Contact.sql)[0m
[2022-10-11 11:01:37,863] {dbt_hook.py:130} INFO - 18:01:37    100090 (42P18): Duplicate row detected during DML action
[2022-10-11 11:01:37,863] {dbt_hook.py:130} INFO - 18:01:37    Row Values: ["364a1d85b9e86f5b04f03f2248246b4d", 6077, "Limited Liability", "Fax", "Nader Group", "325", "Administrative Officer", "Genovera Klawi", "Research and Development", "3/20/1961", "83875552", "Married", "3", "43406-0099", "522", "70cd9330b1d61fd739fb6184e70b6891", 1665399948447000000, 1665399948447000000, NULL]
[2022-10-11 11:01:37,864] {dbt_hook.py:130} INFO - 18:01:37    compiled SQL at target/run/dbt_project/snapshots/Core_Contact.sql
[2022-10-11 11:01:37,865] {dbt_hook.py:130} INFO - 18:01:37
[2022-10-11 11:01:37,866] {dbt_hook.py:130} INFO - 18:01:37  Done. PASS=3 WARN=0 ERROR=2 SKIP=1 TOTAL=6
[2022-10-11 11:01:39,296] {dbt_hook.py:132} INFO - Command exited with return code 1
[2022-10-11 11:01:39,305] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/airflow/airflow_env/lib/python3.8/site-packages/airflow_dbt/operators/dbt_operator.py", line 126, in execute
    self.create_hook().run_cli('snapshot')
  File "/home/ubuntu/airflow/airflow_env/lib/python3.8/site-packages/airflow_dbt/hooks/dbt_hook.py", line 138, in run_cli
    raise AirflowException("dbt command failed")
airflow.exceptions.AirflowException: dbt command failed
[2022-10-11 11:01:39,309] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dbt, task_id=dbt_snapshot, execution_date=20221010T000000, start_date=20221011T180113, end_date=20221011T180139
[2022-10-11 11:01:39,320] {standard_task_runner.py:92} ERROR - Failed to execute job 53 for task dbt_snapshot (dbt command failed; 201872)
[2022-10-11 11:01:39,350] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-11 11:01:39,363] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
