[2022-10-18 00:12:12,498] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dbt.dbt_snapshot scheduled__2022-10-17T00:00:00+00:00 [queued]>
[2022-10-18 00:12:12,508] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dbt.dbt_snapshot scheduled__2022-10-17T00:00:00+00:00 [queued]>
[2022-10-18 00:12:12,508] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-18 00:12:12,509] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-18 00:12:12,509] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-18 00:12:12,524] {taskinstance.py:1377} INFO - Executing <Task(DbtSnapshotOperator): dbt_snapshot> on 2022-10-17 00:00:00+00:00
[2022-10-18 00:12:12,527] {standard_task_runner.py:52} INFO - Started process 265729 to run task
[2022-10-18 00:12:12,532] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dbt', 'dbt_snapshot', 'scheduled__2022-10-17T00:00:00+00:00', '--job-id', '129', '--raw', '--subdir', 'DAGS_FOLDER/dbt_airflow.py', '--cfg-path', '/tmp/tmp4zcucv79', '--error-file', '/tmp/tmpm_x1h_so']
[2022-10-18 00:12:12,533] {standard_task_runner.py:80} INFO - Job 129: Subtask dbt_snapshot
[2022-10-18 00:12:12,582] {task_command.py:370} INFO - Running <TaskInstance: dbt.dbt_snapshot scheduled__2022-10-17T00:00:00+00:00 [running]> on host ubuntu
[2022-10-18 00:12:12,646] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dbt
AIRFLOW_CTX_TASK_ID=dbt_snapshot
AIRFLOW_CTX_EXECUTION_DATE=2022-10-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-17T00:00:00+00:00
[2022-10-18 00:12:12,647] {dbt_hook.py:117} INFO - dbt snapshot
[2022-10-18 00:12:12,653] {dbt_hook.py:126} INFO - Output:
[2022-10-18 00:12:15,269] {dbt_hook.py:130} INFO - 07:12:15  Running with dbt=1.1.0
[2022-10-18 00:12:15,355] {dbt_hook.py:130} INFO - 07:12:15  Found 6 models, 5 tests, 6 snapshots, 0 analyses, 400 macros, 0 operations, 7 seed files, 2 sources, 0 exposures, 0 metrics
[2022-10-18 00:12:15,358] {dbt_hook.py:130} INFO - 07:12:15
[2022-10-18 00:12:18,383] {dbt_hook.py:130} INFO - 07:12:18  Concurrency: 2 threads (target='dev')
[2022-10-18 00:12:18,383] {dbt_hook.py:130} INFO - 07:12:18
[2022-10-18 00:12:18,388] {dbt_hook.py:130} INFO - 07:12:18  1 of 6 START snapshot DBT_HAMS71.Core_Accounts ................................. [RUN]
[2022-10-18 00:12:18,396] {dbt_hook.py:130} INFO - 07:12:18  2 of 6 START snapshot DBT_HAMS71.Core_Address .................................. [RUN]
[2022-10-18 00:12:23,332] {dbt_hook.py:130} INFO - 07:12:23  2 of 6 ERROR snapshotting DBT_HAMS71.Core_Address .............................. [[31mERROR[0m in 4.94s]
[2022-10-18 00:12:23,334] {dbt_hook.py:130} INFO - 07:12:23  3 of 6 START snapshot DBT_HAMS71.Core_Bank ..................................... [RUN]
[2022-10-18 00:12:23,446] {dbt_hook.py:130} INFO - 07:12:23  1 of 6 OK snapshotted DBT_HAMS71.Core_Accounts ................................. [[32mSUCCESS 1[0m in 5.06s]
[2022-10-18 00:12:23,447] {dbt_hook.py:130} INFO - 07:12:23  4 of 6 START snapshot DBT_HAMS71.Core_Branch ................................... [RUN]
[2022-10-18 00:12:27,999] {dbt_hook.py:130} INFO - 07:12:27  4 of 6 OK snapshotted DBT_HAMS71.Core_Branch ................................... [[32mSUCCESS 1[0m in 4.55s]
[2022-10-18 00:12:28,002] {dbt_hook.py:130} INFO - 07:12:28  5 of 6 START snapshot DBT_HAMS71.Core_Contact .................................. [RUN]
[2022-10-18 00:12:28,244] {dbt_hook.py:130} INFO - 07:12:28  3 of 6 OK snapshotted DBT_HAMS71.Core_Bank ..................................... [[32mSUCCESS 1[0m in 4.91s]
[2022-10-18 00:12:34,410] {dbt_hook.py:130} INFO - 07:12:34  5 of 6 ERROR snapshotting DBT_HAMS71.Core_Contact .............................. [[31mERROR[0m in 6.41s]
[2022-10-18 00:12:34,413] {dbt_hook.py:130} INFO - 07:12:34  6 of 6 SKIP relation DBT_HAMS71.Core_Contact_Account_Branch .................... [[33mSKIP[0m]
[2022-10-18 00:12:34,417] {dbt_hook.py:130} INFO - 07:12:34
[2022-10-18 00:12:34,418] {dbt_hook.py:130} INFO - 07:12:34  Finished running 6 snapshots in 19.06s.
[2022-10-18 00:12:34,446] {dbt_hook.py:130} INFO - 07:12:34
[2022-10-18 00:12:34,447] {dbt_hook.py:130} INFO - 07:12:34  [31mCompleted with 2 errors and 0 warnings:[0m
[2022-10-18 00:12:34,448] {dbt_hook.py:130} INFO - 07:12:34
[2022-10-18 00:12:34,449] {dbt_hook.py:130} INFO - 07:12:34  [33mDatabase Error in snapshot Core_Address (snapshots/Core_Address.sql)[0m
[2022-10-18 00:12:34,450] {dbt_hook.py:130} INFO - 07:12:34    100090 (42P18): Duplicate row detected during DML action
[2022-10-18 00:12:34,451] {dbt_hook.py:130} INFO - 07:12:34    Row Values: ["fb89705ae6d743bf1e848c206e16a1d7", "727", 95, "2660 Summit Alley", "92b3ab239bf5a079b6b0430976403097", 1665696227848000000, 1665696227848000000, NULL]
[2022-10-18 00:12:34,452] {dbt_hook.py:130} INFO - 07:12:34    compiled SQL at target/run/dbt_project/snapshots/Core_Address.sql
[2022-10-18 00:12:34,454] {dbt_hook.py:130} INFO - 07:12:34
[2022-10-18 00:12:34,455] {dbt_hook.py:130} INFO - 07:12:34  [33mDatabase Error in snapshot Core_Contact (snapshots/Core_Contact.sql)[0m
[2022-10-18 00:12:34,457] {dbt_hook.py:130} INFO - 07:12:34    100090 (42P18): Duplicate row detected during DML action
[2022-10-18 00:12:34,458] {dbt_hook.py:130} INFO - 07:12:34    Row Values: ["364a1d85b9e86f5b04f03f2248246b4d", 6077, "Limited Liability", "Fax", "Nader Group", "325", "Administrative Officer", "Genovera Klawi", "Research and Development", "3/20/1961", "83875552", "Married", "3", "43406-0099", "522", "55a7144ac633add4eeb8aef0964876e1", 1665696233044000000, 1665696233044000000, NULL]
[2022-10-18 00:12:34,459] {dbt_hook.py:130} INFO - 07:12:34    compiled SQL at target/run/dbt_project/snapshots/Core_Contact.sql
[2022-10-18 00:12:34,459] {dbt_hook.py:130} INFO - 07:12:34
[2022-10-18 00:12:34,460] {dbt_hook.py:130} INFO - 07:12:34  Done. PASS=3 WARN=0 ERROR=2 SKIP=1 TOTAL=6
[2022-10-18 00:12:36,175] {dbt_hook.py:132} INFO - Command exited with return code 1
[2022-10-18 00:12:36,186] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/airflow/airflow_env/lib/python3.8/site-packages/airflow_dbt/operators/dbt_operator.py", line 126, in execute
    self.create_hook().run_cli('snapshot')
  File "/home/ubuntu/airflow/airflow_env/lib/python3.8/site-packages/airflow_dbt/hooks/dbt_hook.py", line 138, in run_cli
    raise AirflowException("dbt command failed")
airflow.exceptions.AirflowException: dbt command failed
[2022-10-18 00:12:36,189] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dbt, task_id=dbt_snapshot, execution_date=20221017T000000, start_date=20221018T071212, end_date=20221018T071236
[2022-10-18 00:12:36,199] {standard_task_runner.py:92} ERROR - Failed to execute job 129 for task dbt_snapshot (dbt command failed; 265729)
[2022-10-18 00:12:36,217] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-18 00:12:36,240] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
