[2022-10-13 12:19:53,734] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dbt.dbt_snapshot scheduled__2022-10-13T00:02:00+00:00 [queued]>
[2022-10-13 12:19:53,742] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dbt.dbt_snapshot scheduled__2022-10-13T00:02:00+00:00 [queued]>
[2022-10-13 12:19:53,742] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-13 12:19:53,742] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-13 12:19:53,742] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-13 12:19:53,771] {taskinstance.py:1377} INFO - Executing <Task(DbtSnapshotOperator): dbt_snapshot> on 2022-10-13 00:02:00+00:00
[2022-10-13 12:19:53,778] {standard_task_runner.py:52} INFO - Started process 237130 to run task
[2022-10-13 12:19:53,783] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dbt', 'dbt_snapshot', 'scheduled__2022-10-13T00:02:00+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/dbt_airflow.py', '--cfg-path', '/tmp/tmpcadypg58', '--error-file', '/tmp/tmpw51t46my']
[2022-10-13 12:19:53,784] {standard_task_runner.py:80} INFO - Job 76: Subtask dbt_snapshot
[2022-10-13 12:19:53,842] {task_command.py:370} INFO - Running <TaskInstance: dbt.dbt_snapshot scheduled__2022-10-13T00:02:00+00:00 [running]> on host ubuntu
[2022-10-13 12:19:53,933] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dbt
AIRFLOW_CTX_TASK_ID=dbt_snapshot
AIRFLOW_CTX_EXECUTION_DATE=2022-10-13T00:02:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-13T00:02:00+00:00
[2022-10-13 12:19:53,939] {dbt_hook.py:117} INFO - dbt snapshot
[2022-10-13 12:19:53,968] {dbt_hook.py:126} INFO - Output:
[2022-10-13 12:19:56,991] {dbt_hook.py:130} INFO - 19:19:56  Running with dbt=1.1.0
[2022-10-13 12:19:57,276] {dbt_hook.py:130} INFO - 19:19:57  Found 6 models, 5 tests, 6 snapshots, 0 analyses, 400 macros, 0 operations, 7 seed files, 2 sources, 0 exposures, 0 metrics
[2022-10-13 12:19:57,280] {dbt_hook.py:130} INFO - 19:19:57
[2022-10-13 12:20:00,329] {dbt_hook.py:130} INFO - 19:20:00  Concurrency: 2 threads (target='dev')
[2022-10-13 12:20:00,329] {dbt_hook.py:130} INFO - 19:20:00
[2022-10-13 12:20:00,335] {dbt_hook.py:130} INFO - 19:20:00  1 of 6 START snapshot DBT_HAMS71.Core_Accounts ................................. [RUN]
[2022-10-13 12:20:00,337] {dbt_hook.py:130} INFO - 19:20:00  2 of 6 START snapshot DBT_HAMS71.Core_Address .................................. [RUN]
[2022-10-13 12:20:05,050] {dbt_hook.py:130} INFO - 19:20:05  1 of 6 OK snapshotted DBT_HAMS71.Core_Accounts ................................. [[32mSUCCESS 1[0m in 4.71s]
[2022-10-13 12:20:05,055] {dbt_hook.py:130} INFO - 19:20:05  3 of 6 START snapshot DBT_HAMS71.Core_Bank ..................................... [RUN]
[2022-10-13 12:20:05,211] {dbt_hook.py:130} INFO - 19:20:05  2 of 6 ERROR snapshotting DBT_HAMS71.Core_Address .............................. [[31mERROR[0m in 4.87s]
[2022-10-13 12:20:05,218] {dbt_hook.py:130} INFO - 19:20:05  4 of 6 START snapshot DBT_HAMS71.Core_Branch ................................... [RUN]
[2022-10-13 12:20:10,320] {dbt_hook.py:130} INFO - 19:20:10  3 of 6 OK snapshotted DBT_HAMS71.Core_Bank ..................................... [[32mSUCCESS 1[0m in 5.26s]
[2022-10-13 12:20:10,323] {dbt_hook.py:130} INFO - 19:20:10  4 of 6 OK snapshotted DBT_HAMS71.Core_Branch ................................... [[32mSUCCESS 1[0m in 5.10s]
[2022-10-13 12:20:10,325] {dbt_hook.py:130} INFO - 19:20:10  5 of 6 START snapshot DBT_HAMS71.Core_Contact .................................. [RUN]
[2022-10-13 12:20:15,257] {dbt_hook.py:130} INFO - 19:20:15  5 of 6 ERROR snapshotting DBT_HAMS71.Core_Contact .............................. [[31mERROR[0m in 4.93s]
[2022-10-13 12:20:15,259] {dbt_hook.py:130} INFO - 19:20:15  6 of 6 SKIP relation DBT_HAMS71.Core_Contact_Account_Branch .................... [[33mSKIP[0m]
[2022-10-13 12:20:15,263] {dbt_hook.py:130} INFO - 19:20:15
[2022-10-13 12:20:15,263] {dbt_hook.py:130} INFO - 19:20:15  Finished running 6 snapshots in 17.98s.
[2022-10-13 12:20:15,276] {dbt_hook.py:130} INFO - 19:20:15
[2022-10-13 12:20:15,277] {dbt_hook.py:130} INFO - 19:20:15  [31mCompleted with 2 errors and 0 warnings:[0m
[2022-10-13 12:20:15,277] {dbt_hook.py:130} INFO - 19:20:15
[2022-10-13 12:20:15,277] {dbt_hook.py:130} INFO - 19:20:15  [33mDatabase Error in snapshot Core_Address (snapshots/Core_Address.sql)[0m
[2022-10-13 12:20:15,277] {dbt_hook.py:130} INFO - 19:20:15    100090 (42P18): Duplicate row detected during DML action
[2022-10-13 12:20:15,278] {dbt_hook.py:130} INFO - 19:20:15    Row Values: ["fb89705ae6d743bf1e848c206e16a1d7", "727", 95, "2660 Summit Alley", "561aee1b5dd67a71c001a164440f11f9", 1665688691644000000, 1665688691644000000, NULL]
[2022-10-13 12:20:15,278] {dbt_hook.py:130} INFO - 19:20:15    compiled SQL at target/run/dbt_project/snapshots/Core_Address.sql
[2022-10-13 12:20:15,278] {dbt_hook.py:130} INFO - 19:20:15
[2022-10-13 12:20:15,278] {dbt_hook.py:130} INFO - 19:20:15  [33mDatabase Error in snapshot Core_Contact (snapshots/Core_Contact.sql)[0m
[2022-10-13 12:20:15,279] {dbt_hook.py:130} INFO - 19:20:15    100090 (42P18): Duplicate row detected during DML action
[2022-10-13 12:20:15,279] {dbt_hook.py:130} INFO - 19:20:15    Row Values: ["364a1d85b9e86f5b04f03f2248246b4d", 6077, "Limited Liability", "Fax", "Nader Group", "325", "Administrative Officer", "Genovera Klawi", "Research and Development", "3/20/1961", "83875552", "Married", "3", "43406-0099", "522", "85fc1fe679d044ab0c293bc0ed8e16fa", 1665688696559000000, 1665688696559000000, NULL]
[2022-10-13 12:20:15,279] {dbt_hook.py:130} INFO - 19:20:15    compiled SQL at target/run/dbt_project/snapshots/Core_Contact.sql
[2022-10-13 12:20:15,280] {dbt_hook.py:130} INFO - 19:20:15
[2022-10-13 12:20:15,280] {dbt_hook.py:130} INFO - 19:20:15  Done. PASS=3 WARN=0 ERROR=2 SKIP=1 TOTAL=6
[2022-10-13 12:20:16,811] {dbt_hook.py:132} INFO - Command exited with return code 1
[2022-10-13 12:20:16,821] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/airflow/airflow_env/lib/python3.8/site-packages/airflow_dbt/operators/dbt_operator.py", line 126, in execute
    self.create_hook().run_cli('snapshot')
  File "/home/ubuntu/airflow/airflow_env/lib/python3.8/site-packages/airflow_dbt/hooks/dbt_hook.py", line 138, in run_cli
    raise AirflowException("dbt command failed")
airflow.exceptions.AirflowException: dbt command failed
[2022-10-13 12:20:16,825] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dbt, task_id=dbt_snapshot, execution_date=20221013T000200, start_date=20221013T191953, end_date=20221013T192016
[2022-10-13 12:20:16,838] {standard_task_runner.py:92} ERROR - Failed to execute job 76 for task dbt_snapshot (dbt command failed; 237130)
[2022-10-13 12:20:16,867] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-13 12:20:16,890] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
