[2022-10-10 00:56:35,268] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dbt.dbt_snapshot manual__2022-10-10T07:55:40.237822+00:00 [queued]>
[2022-10-10 00:56:35,275] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dbt.dbt_snapshot manual__2022-10-10T07:55:40.237822+00:00 [queued]>
[2022-10-10 00:56:35,275] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-10 00:56:35,275] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-10 00:56:35,275] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-10 00:56:35,289] {taskinstance.py:1377} INFO - Executing <Task(DbtSnapshotOperator): dbt_snapshot> on 2022-10-10 07:55:40.237822+00:00
[2022-10-10 00:56:35,292] {standard_task_runner.py:52} INFO - Started process 166584 to run task
[2022-10-10 00:56:35,300] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dbt', 'dbt_snapshot', 'manual__2022-10-10T07:55:40.237822+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/dbt_airflow.py', '--cfg-path', '/tmp/tmp12_dkivt', '--error-file', '/tmp/tmpx0gei4dq']
[2022-10-10 00:56:35,301] {standard_task_runner.py:80} INFO - Job 20: Subtask dbt_snapshot
[2022-10-10 00:56:35,349] {task_command.py:370} INFO - Running <TaskInstance: dbt.dbt_snapshot manual__2022-10-10T07:55:40.237822+00:00 [running]> on host ubuntu
[2022-10-10 00:56:35,388] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dbt
AIRFLOW_CTX_TASK_ID=dbt_snapshot
AIRFLOW_CTX_EXECUTION_DATE=2022-10-10T07:55:40.237822+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-10T07:55:40.237822+00:00
[2022-10-10 00:56:35,388] {dbt_hook.py:117} INFO - dbt snapshot
[2022-10-10 00:56:35,393] {dbt_hook.py:126} INFO - Output:
[2022-10-10 00:56:38,314] {dbt_hook.py:130} INFO - 07:56:38  Running with dbt=1.1.0
[2022-10-10 00:56:38,392] {dbt_hook.py:130} INFO - 07:56:38  Found 6 models, 5 tests, 7 snapshots, 0 analyses, 400 macros, 0 operations, 7 seed files, 2 sources, 0 exposures, 0 metrics
[2022-10-10 00:56:38,395] {dbt_hook.py:130} INFO - 07:56:38
[2022-10-10 00:56:41,421] {dbt_hook.py:130} INFO - 07:56:41  Concurrency: 2 threads (target='dev')
[2022-10-10 00:56:41,421] {dbt_hook.py:130} INFO - 07:56:41
[2022-10-10 00:56:41,426] {dbt_hook.py:130} INFO - 07:56:41  1 of 7 START snapshot Stage_Schema.Core_Accounts ............................... [RUN]
[2022-10-10 00:56:41,427] {dbt_hook.py:130} INFO - 07:56:41  2 of 7 START snapshot Stage_Schema.Core_Address ................................ [RUN]
[2022-10-10 00:56:46,393] {dbt_hook.py:130} INFO - 07:56:46  2 of 7 ERROR snapshotting Stage_Schema.Core_Address ............................ [[31mERROR[0m in 4.96s]
[2022-10-10 00:56:46,394] {dbt_hook.py:130} INFO - 07:56:46  3 of 7 START snapshot Stage_Schema.Core_Bank ................................... [RUN]
[2022-10-10 00:56:46,433] {dbt_hook.py:130} INFO - 07:56:46  1 of 7 OK snapshotted Stage_Schema.Core_Accounts ............................... [[32mSUCCESS 1[0m in 5.01s]
[2022-10-10 00:56:46,434] {dbt_hook.py:130} INFO - 07:56:46  4 of 7 START snapshot Stage_Schema.Core_Branch ................................. [RUN]
[2022-10-10 00:56:51,184] {dbt_hook.py:130} INFO - 07:56:51  3 of 7 OK snapshotted Stage_Schema.Core_Bank ................................... [[32mSUCCESS 1[0m in 4.79s]
[2022-10-10 00:56:51,185] {dbt_hook.py:130} INFO - 07:56:51  5 of 7 START snapshot Stage_Schema.Core_Contact ................................ [RUN]
[2022-10-10 00:56:51,256] {dbt_hook.py:130} INFO - 07:56:51  4 of 7 OK snapshotted Stage_Schema.Core_Branch ................................. [[32mSUCCESS 1[0m in 4.82s]
[2022-10-10 00:56:51,257] {dbt_hook.py:130} INFO - 07:56:51  6 of 7 START snapshot Stage_Schema.name_history ................................ [RUN]
[2022-10-10 00:56:56,176] {dbt_hook.py:130} INFO - 07:56:56  6 of 7 OK snapshotted Stage_Schema.name_history ................................ [[32mSUCCESS 1[0m in 4.92s]
[2022-10-10 00:56:56,836] {dbt_hook.py:130} INFO - 07:56:56  5 of 7 ERROR snapshotting Stage_Schema.Core_Contact ............................ [[31mERROR[0m in 5.65s]
[2022-10-10 00:56:56,838] {dbt_hook.py:130} INFO - 07:56:56  7 of 7 SKIP relation Stage_Schema.Core_Contact_Account_Branch .................. [[33mSKIP[0m]
[2022-10-10 00:56:56,841] {dbt_hook.py:130} INFO - 07:56:56
[2022-10-10 00:56:56,841] {dbt_hook.py:130} INFO - 07:56:56  Finished running 7 snapshots in 18.44s.
[2022-10-10 00:56:56,856] {dbt_hook.py:130} INFO - 07:56:56
[2022-10-10 00:56:56,856] {dbt_hook.py:130} INFO - 07:56:56  [31mCompleted with 2 errors and 0 warnings:[0m
[2022-10-10 00:56:56,857] {dbt_hook.py:130} INFO - 07:56:56
[2022-10-10 00:56:56,857] {dbt_hook.py:130} INFO - 07:56:56  [33mDatabase Error in snapshot Core_Address (snapshots/Core_Address.sql)[0m
[2022-10-10 00:56:56,857] {dbt_hook.py:130} INFO - 07:56:56    100090 (42P18): Duplicate row detected during DML action
[2022-10-10 00:56:56,857] {dbt_hook.py:130} INFO - 07:56:56    Row Values: ["fb89705ae6d743bf1e848c206e16a1d7", "727", 95, "2660 Summit Alley", "fbf482376582654ae3b9f39bc256551f", 1665085635285000000, 1665085635285000000, NULL]
[2022-10-10 00:56:56,858] {dbt_hook.py:130} INFO - 07:56:56    compiled SQL at target/run/dbt_project/snapshots/Core_Address.sql
[2022-10-10 00:56:56,858] {dbt_hook.py:130} INFO - 07:56:56
[2022-10-10 00:56:56,858] {dbt_hook.py:130} INFO - 07:56:56  [33mDatabase Error in snapshot Core_Contact (snapshots/Core_Contact.sql)[0m
[2022-10-10 00:56:56,859] {dbt_hook.py:130} INFO - 07:56:56    100090 (42P18): Duplicate row detected during DML action
[2022-10-10 00:56:56,859] {dbt_hook.py:130} INFO - 07:56:56    Row Values: ["364a1d85b9e86f5b04f03f2248246b4d", 6077, "Limited Liability", "Fax", "Nader Group", "325", "Administrative Officer", "Genovera Klawi", "Research and Development", "3/20/1961", "83875552", "Married", "3", "43406-0099", "522", "8df583ffb305c1a50d40c00fce4c1e06", 1665085533216000000, 1665085533216000000, NULL]
[2022-10-10 00:56:56,859] {dbt_hook.py:130} INFO - 07:56:56    compiled SQL at target/run/dbt_project/snapshots/Core_Contact.sql
[2022-10-10 00:56:56,860] {dbt_hook.py:130} INFO - 07:56:56
[2022-10-10 00:56:56,860] {dbt_hook.py:130} INFO - 07:56:56  Done. PASS=4 WARN=0 ERROR=2 SKIP=1 TOTAL=7
[2022-10-10 00:56:58,305] {dbt_hook.py:132} INFO - Command exited with return code 1
[2022-10-10 00:56:58,313] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/airflow/airflow_env/lib/python3.8/site-packages/airflow_dbt/operators/dbt_operator.py", line 126, in execute
    self.create_hook().run_cli('snapshot')
  File "/home/ubuntu/airflow/airflow_env/lib/python3.8/site-packages/airflow_dbt/hooks/dbt_hook.py", line 138, in run_cli
    raise AirflowException("dbt command failed")
airflow.exceptions.AirflowException: dbt command failed
[2022-10-10 00:56:58,316] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dbt, task_id=dbt_snapshot, execution_date=20221010T075540, start_date=20221010T075635, end_date=20221010T075658
[2022-10-10 00:56:58,325] {standard_task_runner.py:92} ERROR - Failed to execute job 20 for task dbt_snapshot (dbt command failed; 166584)
[2022-10-10 00:56:58,348] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-10 00:56:58,364] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
