[2022-10-17 11:04:53,368] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dbt.dbt_snapshot scheduled__2022-10-16T00:00:00+00:00 [queued]>
[2022-10-17 11:04:53,373] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dbt.dbt_snapshot scheduled__2022-10-16T00:00:00+00:00 [queued]>
[2022-10-17 11:04:53,373] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-17 11:04:53,374] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-17 11:04:53,374] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-17 11:04:53,387] {taskinstance.py:1377} INFO - Executing <Task(DbtSnapshotOperator): dbt_snapshot> on 2022-10-16 00:00:00+00:00
[2022-10-17 11:04:53,390] {standard_task_runner.py:52} INFO - Started process 263427 to run task
[2022-10-17 11:04:53,394] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dbt', 'dbt_snapshot', 'scheduled__2022-10-16T00:00:00+00:00', '--job-id', '122', '--raw', '--subdir', 'DAGS_FOLDER/dbt_airflow.py', '--cfg-path', '/tmp/tmpxm3kyz47', '--error-file', '/tmp/tmp_7apqryk']
[2022-10-17 11:04:53,394] {standard_task_runner.py:80} INFO - Job 122: Subtask dbt_snapshot
[2022-10-17 11:04:53,436] {task_command.py:370} INFO - Running <TaskInstance: dbt.dbt_snapshot scheduled__2022-10-16T00:00:00+00:00 [running]> on host ubuntu
[2022-10-17 11:04:53,490] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dbt
AIRFLOW_CTX_TASK_ID=dbt_snapshot
AIRFLOW_CTX_EXECUTION_DATE=2022-10-16T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-16T00:00:00+00:00
[2022-10-17 11:04:53,491] {dbt_hook.py:117} INFO - dbt snapshot
[2022-10-17 11:04:53,497] {dbt_hook.py:126} INFO - Output:
[2022-10-17 11:04:56,254] {dbt_hook.py:130} INFO - 18:04:56  Running with dbt=1.1.0
[2022-10-17 11:04:56,357] {dbt_hook.py:130} INFO - 18:04:56  Found 6 models, 5 tests, 6 snapshots, 0 analyses, 400 macros, 0 operations, 7 seed files, 2 sources, 0 exposures, 0 metrics
[2022-10-17 11:04:56,359] {dbt_hook.py:130} INFO - 18:04:56
[2022-10-17 11:04:59,307] {dbt_hook.py:130} INFO - 18:04:59  Concurrency: 2 threads (target='dev')
[2022-10-17 11:04:59,307] {dbt_hook.py:130} INFO - 18:04:59
[2022-10-17 11:04:59,314] {dbt_hook.py:130} INFO - 18:04:59  1 of 6 START snapshot DBT_HAMS71.Core_Accounts ................................. [RUN]
[2022-10-17 11:04:59,315] {dbt_hook.py:130} INFO - 18:04:59  2 of 6 START snapshot DBT_HAMS71.Core_Address .................................. [RUN]
[2022-10-17 11:05:04,078] {dbt_hook.py:130} INFO - 18:05:04  1 of 6 OK snapshotted DBT_HAMS71.Core_Accounts ................................. [[32mSUCCESS 1[0m in 4.76s]
[2022-10-17 11:05:04,081] {dbt_hook.py:130} INFO - 18:05:04  3 of 6 START snapshot DBT_HAMS71.Core_Bank ..................................... [RUN]
[2022-10-17 11:05:04,298] {dbt_hook.py:130} INFO - 18:05:04  2 of 6 ERROR snapshotting DBT_HAMS71.Core_Address .............................. [[31mERROR[0m in 4.98s]
[2022-10-17 11:05:04,300] {dbt_hook.py:130} INFO - 18:05:04  4 of 6 START snapshot DBT_HAMS71.Core_Branch ................................... [RUN]
[2022-10-17 11:05:09,068] {dbt_hook.py:130} INFO - 18:05:09  4 of 6 OK snapshotted DBT_HAMS71.Core_Branch ................................... [[32mSUCCESS 1[0m in 4.77s]
[2022-10-17 11:05:09,069] {dbt_hook.py:130} INFO - 18:05:09  5 of 6 START snapshot DBT_HAMS71.Core_Contact .................................. [RUN]
[2022-10-17 11:05:09,620] {dbt_hook.py:130} INFO - 18:05:09  3 of 6 OK snapshotted DBT_HAMS71.Core_Bank ..................................... [[32mSUCCESS 1[0m in 5.54s]
[2022-10-17 11:05:14,431] {dbt_hook.py:130} INFO - 18:05:14  5 of 6 ERROR snapshotting DBT_HAMS71.Core_Contact .............................. [[31mERROR[0m in 5.36s]
[2022-10-17 11:05:14,433] {dbt_hook.py:130} INFO - 18:05:14  6 of 6 SKIP relation DBT_HAMS71.Core_Contact_Account_Branch .................... [[33mSKIP[0m]
[2022-10-17 11:05:14,435] {dbt_hook.py:130} INFO - 18:05:14
[2022-10-17 11:05:14,436] {dbt_hook.py:130} INFO - 18:05:14  Finished running 6 snapshots in 18.08s.
[2022-10-17 11:05:14,456] {dbt_hook.py:130} INFO - 18:05:14
[2022-10-17 11:05:14,456] {dbt_hook.py:130} INFO - 18:05:14  [31mCompleted with 2 errors and 0 warnings:[0m
[2022-10-17 11:05:14,456] {dbt_hook.py:130} INFO - 18:05:14
[2022-10-17 11:05:14,457] {dbt_hook.py:130} INFO - 18:05:14  [33mDatabase Error in snapshot Core_Address (snapshots/Core_Address.sql)[0m
[2022-10-17 11:05:14,457] {dbt_hook.py:130} INFO - 18:05:14    100090 (42P18): Duplicate row detected during DML action
[2022-10-17 11:05:14,457] {dbt_hook.py:130} INFO - 18:05:14    Row Values: ["fb89705ae6d743bf1e848c206e16a1d7", "727", 95, "2660 Summit Alley", "92b3ab239bf5a079b6b0430976403097", 1665696227848000000, 1665696227848000000, NULL]
[2022-10-17 11:05:14,458] {dbt_hook.py:130} INFO - 18:05:14    compiled SQL at target/run/dbt_project/snapshots/Core_Address.sql
[2022-10-17 11:05:14,458] {dbt_hook.py:130} INFO - 18:05:14
[2022-10-17 11:05:14,458] {dbt_hook.py:130} INFO - 18:05:14  [33mDatabase Error in snapshot Core_Contact (snapshots/Core_Contact.sql)[0m
[2022-10-17 11:05:14,459] {dbt_hook.py:130} INFO - 18:05:14    100090 (42P18): Duplicate row detected during DML action
[2022-10-17 11:05:14,459] {dbt_hook.py:130} INFO - 18:05:14    Row Values: ["364a1d85b9e86f5b04f03f2248246b4d", 6077, "Limited Liability", "Fax", "Nader Group", "325", "Administrative Officer", "Genovera Klawi", "Research and Development", "3/20/1961", "83875552", "Married", "3", "43406-0099", "522", "55a7144ac633add4eeb8aef0964876e1", 1665696233044000000, 1665696233044000000, NULL]
[2022-10-17 11:05:14,459] {dbt_hook.py:130} INFO - 18:05:14    compiled SQL at target/run/dbt_project/snapshots/Core_Contact.sql
[2022-10-17 11:05:14,460] {dbt_hook.py:130} INFO - 18:05:14
[2022-10-17 11:05:14,460] {dbt_hook.py:130} INFO - 18:05:14  Done. PASS=3 WARN=0 ERROR=2 SKIP=1 TOTAL=6
[2022-10-17 11:05:16,082] {dbt_hook.py:132} INFO - Command exited with return code 1
[2022-10-17 11:05:16,092] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/airflow/airflow_env/lib/python3.8/site-packages/airflow_dbt/operators/dbt_operator.py", line 126, in execute
    self.create_hook().run_cli('snapshot')
  File "/home/ubuntu/airflow/airflow_env/lib/python3.8/site-packages/airflow_dbt/hooks/dbt_hook.py", line 138, in run_cli
    raise AirflowException("dbt command failed")
airflow.exceptions.AirflowException: dbt command failed
[2022-10-17 11:05:16,095] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dbt, task_id=dbt_snapshot, execution_date=20221016T000000, start_date=20221017T180453, end_date=20221017T180516
[2022-10-17 11:05:16,106] {standard_task_runner.py:92} ERROR - Failed to execute job 122 for task dbt_snapshot (dbt command failed; 263427)
[2022-10-17 11:05:16,112] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-17 11:05:16,131] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
