[2022-10-13 12:53:42,427] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dbt_dag_bash.dbt_run manual__2022-10-13T19:53:16.900766+00:00 [queued]>
[2022-10-13 12:53:42,432] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dbt_dag_bash.dbt_run manual__2022-10-13T19:53:16.900766+00:00 [queued]>
[2022-10-13 12:53:42,432] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-13 12:53:42,432] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-13 12:53:42,432] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-13 12:53:42,442] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): dbt_run> on 2022-10-13 19:53:16.900766+00:00
[2022-10-13 12:53:42,445] {standard_task_runner.py:52} INFO - Started process 242005 to run task
[2022-10-13 12:53:42,449] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_dag_bash', 'dbt_run', 'manual__2022-10-13T19:53:16.900766+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/dbt_bashOperator.py', '--cfg-path', '/tmp/tmp9xbnt8sr', '--error-file', '/tmp/tmpb906ku_x']
[2022-10-13 12:53:42,450] {standard_task_runner.py:80} INFO - Job 83: Subtask dbt_run
[2022-10-13 12:53:42,485] {task_command.py:370} INFO - Running <TaskInstance: dbt_dag_bash.dbt_run manual__2022-10-13T19:53:16.900766+00:00 [running]> on host ubuntu
[2022-10-13 12:53:42,524] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dbt_dag_bash
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2022-10-13T19:53:16.900766+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-13T19:53:16.900766+00:00
[2022-10-13 12:53:42,525] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-10-13 12:53:42,526] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'dbt run -m Core']
[2022-10-13 12:53:42,534] {subprocess.py:85} INFO - Output:
[2022-10-13 12:53:45,105] {subprocess.py:92} INFO - 19:53:45  Encountered an error:
[2022-10-13 12:53:45,105] {subprocess.py:92} INFO - Runtime Error
[2022-10-13 12:53:45,105] {subprocess.py:92} INFO -   fatal: Not a dbt project (or any of the parent directories). Missing dbt_project.yml file
[2022-10-13 12:53:45,212] {subprocess.py:96} INFO - Command exited with return code 2
[2022-10-13 12:53:45,221] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/airflow/airflow_env/lib/python3.8/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-10-13 12:53:45,224] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dbt_dag_bash, task_id=dbt_run, execution_date=20221013T195316, start_date=20221013T195342, end_date=20221013T195345
[2022-10-13 12:53:45,233] {standard_task_runner.py:92} ERROR - Failed to execute job 83 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 242005)
[2022-10-13 12:53:45,239] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-13 12:53:45,261] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
