[2022-10-10 00:48:50,151] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dbt.dbt_seed manual__2022-10-10T07:48:47.871073+00:00 [queued]>
[2022-10-10 00:48:50,156] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dbt.dbt_seed manual__2022-10-10T07:48:47.871073+00:00 [queued]>
[2022-10-10 00:48:50,156] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-10 00:48:50,156] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-10 00:48:50,157] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-10 00:48:50,177] {taskinstance.py:1377} INFO - Executing <Task(DbtSeedOperator): dbt_seed> on 2022-10-10 07:48:47.871073+00:00
[2022-10-10 00:48:50,180] {standard_task_runner.py:52} INFO - Started process 164558 to run task
[2022-10-10 00:48:50,191] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dbt', 'dbt_seed', 'manual__2022-10-10T07:48:47.871073+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/dbt_airflow.py', '--cfg-path', '/tmp/tmp9xud0xvc', '--error-file', '/tmp/tmpuqk0ze8b']
[2022-10-10 00:48:50,192] {standard_task_runner.py:80} INFO - Job 16: Subtask dbt_seed
[2022-10-10 00:48:50,297] {task_command.py:370} INFO - Running <TaskInstance: dbt.dbt_seed manual__2022-10-10T07:48:47.871073+00:00 [running]> on host ubuntu
[2022-10-10 00:48:50,458] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dbt
AIRFLOW_CTX_TASK_ID=dbt_seed
AIRFLOW_CTX_EXECUTION_DATE=2022-10-10T07:48:47.871073+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-10T07:48:47.871073+00:00
[2022-10-10 00:48:50,459] {dbt_hook.py:117} INFO - dbt seed
[2022-10-10 00:48:50,472] {dbt_hook.py:126} INFO - Output:
[2022-10-10 00:48:57,808] {dbt_hook.py:130} INFO - 07:48:57  Running with dbt=1.1.0
[2022-10-10 00:48:57,828] {dbt_hook.py:130} INFO - 07:48:57  Partial parse save file not found. Starting full parse.
[2022-10-10 00:48:58,604] {dbt_hook.py:130} INFO - 07:48:58  Found 2 models, 4 tests, 0 snapshots, 0 analyses, 181 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics
[2022-10-10 00:48:58,606] {dbt_hook.py:130} INFO - 07:48:58
[2022-10-10 00:48:58,607] {dbt_hook.py:130} INFO - 07:48:58  [[33mWARNING[0m]: Nothing to do. Try checking your model configs and model specification args
[2022-10-10 00:48:58,613] {dbt_hook.py:130} INFO - 07:48:58
[2022-10-10 00:48:58,613] {dbt_hook.py:130} INFO - 07:48:58  [32mCompleted successfully[0m
[2022-10-10 00:48:58,613] {dbt_hook.py:130} INFO - 07:48:58
[2022-10-10 00:48:58,614] {dbt_hook.py:130} INFO - 07:48:58  Done. PASS=0 WARN=0 ERROR=0 SKIP=0 TOTAL=0
[2022-10-10 00:48:58,618] {dbt_hook.py:130} INFO - 07:48:58  Error sending message, disabling tracking
[2022-10-10 00:48:58,887] {dbt_hook.py:132} INFO - Command exited with return code 0
[2022-10-10 00:48:58,898] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dbt, task_id=dbt_seed, execution_date=20221010T074847, start_date=20221010T074850, end_date=20221010T074858
[2022-10-10 00:48:58,942] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-10 00:48:58,971] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
