[2022-10-13 14:16:21,920] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dbt_dag_bash.dbt_run manual__2022-10-13T21:15:53.464353+00:00 [queued]>
[2022-10-13 14:16:21,925] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dbt_dag_bash.dbt_run manual__2022-10-13T21:15:53.464353+00:00 [queued]>
[2022-10-13 14:16:21,925] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-13 14:16:21,925] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-13 14:16:21,925] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-13 14:16:21,939] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): dbt_run> on 2022-10-13 21:15:53.464353+00:00
[2022-10-13 14:16:21,942] {standard_task_runner.py:52} INFO - Started process 248924 to run task
[2022-10-13 14:16:21,947] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_dag_bash', 'dbt_run', 'manual__2022-10-13T21:15:53.464353+00:00', '--job-id', '85', '--raw', '--subdir', 'DAGS_FOLDER/dbt_bashOperator.py', '--cfg-path', '/tmp/tmpxfq7z68b', '--error-file', '/tmp/tmpy4wujw1x']
[2022-10-13 14:16:21,947] {standard_task_runner.py:80} INFO - Job 85: Subtask dbt_run
[2022-10-13 14:16:21,991] {task_command.py:370} INFO - Running <TaskInstance: dbt_dag_bash.dbt_run manual__2022-10-13T21:15:53.464353+00:00 [running]> on host ubuntu
[2022-10-13 14:16:22,043] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dbt_dag_bash
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2022-10-13T21:15:53.464353+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-13T21:15:53.464353+00:00
[2022-10-13 14:16:22,044] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-10-13 14:16:22,044] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'dbt run -m Core']
[2022-10-13 14:16:22,053] {subprocess.py:85} INFO - Output:
[2022-10-13 14:16:24,532] {subprocess.py:92} INFO - 21:16:24  Encountered an error:
[2022-10-13 14:16:24,532] {subprocess.py:92} INFO - Runtime Error
[2022-10-13 14:16:24,532] {subprocess.py:92} INFO -   fatal: Not a dbt project (or any of the parent directories). Missing dbt_project.yml file
[2022-10-13 14:16:24,724] {subprocess.py:96} INFO - Command exited with return code 2
[2022-10-13 14:16:24,736] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/airflow/airflow_env/lib/python3.8/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-10-13 14:16:24,739] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dbt_dag_bash, task_id=dbt_run, execution_date=20221013T211553, start_date=20221013T211621, end_date=20221013T211624
[2022-10-13 14:16:24,748] {standard_task_runner.py:92} ERROR - Failed to execute job 85 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 248924)
[2022-10-13 14:16:24,758] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-13 14:16:24,783] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
