[2022-10-10 01:25:32,197] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dbt.dbt_snapshot manual__2022-10-10T08:24:54.129313+00:00 [queued]>
[2022-10-10 01:25:32,204] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dbt.dbt_snapshot manual__2022-10-10T08:24:54.129313+00:00 [queued]>
[2022-10-10 01:25:32,204] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-10 01:25:32,204] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-10 01:25:32,205] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-10 01:25:32,219] {taskinstance.py:1377} INFO - Executing <Task(DbtSnapshotOperator): dbt_snapshot> on 2022-10-10 08:24:54.129313+00:00
[2022-10-10 01:25:32,224] {standard_task_runner.py:52} INFO - Started process 171821 to run task
[2022-10-10 01:25:32,230] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dbt', 'dbt_snapshot', 'manual__2022-10-10T08:24:54.129313+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/dbt_airflow.py', '--cfg-path', '/tmp/tmpz_4whzw4', '--error-file', '/tmp/tmpu_f6bxxy']
[2022-10-10 01:25:32,231] {standard_task_runner.py:80} INFO - Job 32: Subtask dbt_snapshot
[2022-10-10 01:25:32,278] {task_command.py:370} INFO - Running <TaskInstance: dbt.dbt_snapshot manual__2022-10-10T08:24:54.129313+00:00 [running]> on host ubuntu
[2022-10-10 01:25:32,320] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dbt
AIRFLOW_CTX_TASK_ID=dbt_snapshot
AIRFLOW_CTX_EXECUTION_DATE=2022-10-10T08:24:54.129313+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-10T08:24:54.129313+00:00
[2022-10-10 01:25:32,321] {dbt_hook.py:117} INFO - dbt snapshot
[2022-10-10 01:25:32,328] {dbt_hook.py:126} INFO - Output:
[2022-10-10 01:25:34,964] {dbt_hook.py:130} INFO - 08:25:34  Running with dbt=1.1.0
[2022-10-10 01:25:35,045] {dbt_hook.py:130} INFO - 08:25:35  Found 6 models, 5 tests, 7 snapshots, 0 analyses, 400 macros, 0 operations, 7 seed files, 2 sources, 0 exposures, 0 metrics
[2022-10-10 01:25:35,047] {dbt_hook.py:130} INFO - 08:25:35
[2022-10-10 01:25:39,744] {dbt_hook.py:130} INFO - 08:25:39  Concurrency: 2 threads (target='dev')
[2022-10-10 01:25:39,745] {dbt_hook.py:130} INFO - 08:25:39
[2022-10-10 01:25:39,750] {dbt_hook.py:130} INFO - 08:25:39  1 of 7 START snapshot Stage_Schema.Core_Accounts ............................... [RUN]
[2022-10-10 01:25:39,765] {dbt_hook.py:130} INFO - 08:25:39  2 of 7 START snapshot Stage_Schema.Core_Address ................................ [RUN]
[2022-10-10 01:25:41,878] {dbt_hook.py:130} INFO - 08:25:41  2 of 7 OK snapshotted Stage_Schema.Core_Address ................................ [[32mSUCCESS 1[0m in 2.11s]
[2022-10-10 01:25:41,879] {dbt_hook.py:130} INFO - 08:25:41  3 of 7 START snapshot Stage_Schema.Core_Bank ................................... [RUN]
[2022-10-10 01:25:41,932] {dbt_hook.py:130} INFO - 08:25:41  1 of 7 OK snapshotted Stage_Schema.Core_Accounts ............................... [[32mSUCCESS 1[0m in 2.18s]
[2022-10-10 01:25:41,946] {dbt_hook.py:130} INFO - 08:25:41  4 of 7 START snapshot Stage_Schema.Core_Branch ................................. [RUN]
[2022-10-10 01:25:44,459] {dbt_hook.py:130} INFO - 08:25:44  3 of 7 OK snapshotted Stage_Schema.Core_Bank ................................... [[32mSUCCESS 1[0m in 2.58s]
[2022-10-10 01:25:44,460] {dbt_hook.py:130} INFO - 08:25:44  5 of 7 START snapshot Stage_Schema.Core_Contact ................................ [RUN]
[2022-10-10 01:25:44,604] {dbt_hook.py:130} INFO - 08:25:44  4 of 7 OK snapshotted Stage_Schema.Core_Branch ................................. [[32mSUCCESS 1[0m in 2.66s]
[2022-10-10 01:25:44,606] {dbt_hook.py:130} INFO - 08:25:44  6 of 7 START snapshot Stage_Schema.name_history ................................ [RUN]
[2022-10-10 01:25:45,914] {dbt_hook.py:130} INFO - 08:25:45  6 of 7 ERROR snapshotting Stage_Schema.name_history ............................ [[31mERROR[0m in 1.31s]
[2022-10-10 01:25:46,534] {dbt_hook.py:130} INFO - 08:25:46  5 of 7 OK snapshotted Stage_Schema.Core_Contact ................................ [[32mSUCCESS 1[0m in 2.07s]
[2022-10-10 01:25:46,536] {dbt_hook.py:130} INFO - 08:25:46  7 of 7 START snapshot Stage_Schema.Core_Contact_Account_Branch ................. [RUN]
[2022-10-10 01:25:50,186] {dbt_hook.py:130} INFO - 08:25:50  7 of 7 OK snapshotted Stage_Schema.Core_Contact_Account_Branch ................. [[32mSUCCESS 1[0m in 3.65s]
[2022-10-10 01:25:50,188] {dbt_hook.py:130} INFO - 08:25:50
[2022-10-10 01:25:50,189] {dbt_hook.py:130} INFO - 08:25:50  Finished running 7 snapshots in 15.14s.
[2022-10-10 01:25:50,205] {dbt_hook.py:130} INFO - 08:25:50
[2022-10-10 01:25:50,206] {dbt_hook.py:130} INFO - 08:25:50  [31mCompleted with 1 error and 0 warnings:[0m
[2022-10-10 01:25:50,207] {dbt_hook.py:130} INFO - 08:25:50
[2022-10-10 01:25:50,207] {dbt_hook.py:130} INFO - 08:25:50  [33mDatabase Error in snapshot name_history (snapshots/name_history.sql)[0m
[2022-10-10 01:25:50,208] {dbt_hook.py:130} INFO - 08:25:50    002003 (42S02): SQL compilation error:
[2022-10-10 01:25:50,208] {dbt_hook.py:130} INFO - 08:25:50    Object 'STAGING.DBT_HAMS71.MY_FIRST_DBT_MODEL' does not exist or not authorized.
[2022-10-10 01:25:50,209] {dbt_hook.py:130} INFO - 08:25:50
[2022-10-10 01:25:50,209] {dbt_hook.py:130} INFO - 08:25:50  Done. PASS=6 WARN=0 ERROR=1 SKIP=0 TOTAL=7
[2022-10-10 01:25:51,688] {dbt_hook.py:132} INFO - Command exited with return code 1
[2022-10-10 01:25:51,701] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/airflow/airflow_env/lib/python3.8/site-packages/airflow_dbt/operators/dbt_operator.py", line 126, in execute
    self.create_hook().run_cli('snapshot')
  File "/home/ubuntu/airflow/airflow_env/lib/python3.8/site-packages/airflow_dbt/hooks/dbt_hook.py", line 138, in run_cli
    raise AirflowException("dbt command failed")
airflow.exceptions.AirflowException: dbt command failed
[2022-10-10 01:25:51,704] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dbt, task_id=dbt_snapshot, execution_date=20221010T082454, start_date=20221010T082532, end_date=20221010T082551
[2022-10-10 01:25:51,718] {standard_task_runner.py:92} ERROR - Failed to execute job 32 for task dbt_snapshot (dbt command failed; 171821)
[2022-10-10 01:25:51,732] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-10 01:25:51,756] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
