[2022-10-17 11:00:00,302] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dbt.dbt_snapshot scheduled__2022-10-13T00:04:00+00:00 [queued]>
[2022-10-17 11:00:00,310] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dbt.dbt_snapshot scheduled__2022-10-13T00:04:00+00:00 [queued]>
[2022-10-17 11:00:00,311] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-17 11:00:00,311] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-17 11:00:00,311] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-17 11:00:00,328] {taskinstance.py:1377} INFO - Executing <Task(DbtSnapshotOperator): dbt_snapshot> on 2022-10-13 00:04:00+00:00
[2022-10-17 11:00:00,332] {standard_task_runner.py:52} INFO - Started process 261122 to run task
[2022-10-17 11:00:00,337] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dbt', 'dbt_snapshot', 'scheduled__2022-10-13T00:04:00+00:00', '--job-id', '113', '--raw', '--subdir', 'DAGS_FOLDER/dbt_airflow.py', '--cfg-path', '/tmp/tmpraij3ewz', '--error-file', '/tmp/tmpnc2mpgef']
[2022-10-17 11:00:00,338] {standard_task_runner.py:80} INFO - Job 113: Subtask dbt_snapshot
[2022-10-17 11:00:00,399] {task_command.py:370} INFO - Running <TaskInstance: dbt.dbt_snapshot scheduled__2022-10-13T00:04:00+00:00 [running]> on host ubuntu
[2022-10-17 11:00:00,443] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dbt
AIRFLOW_CTX_TASK_ID=dbt_snapshot
AIRFLOW_CTX_EXECUTION_DATE=2022-10-13T00:04:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-13T00:04:00+00:00
[2022-10-17 11:00:00,444] {dbt_hook.py:117} INFO - dbt snapshot
[2022-10-17 11:00:00,449] {dbt_hook.py:126} INFO - Output:
[2022-10-17 11:00:03,706] {dbt_hook.py:130} INFO - 18:00:03  Running with dbt=1.1.0
[2022-10-17 11:00:03,839] {dbt_hook.py:130} INFO - 18:00:03  Found 6 models, 5 tests, 6 snapshots, 0 analyses, 400 macros, 0 operations, 7 seed files, 2 sources, 0 exposures, 0 metrics
[2022-10-17 11:00:03,843] {dbt_hook.py:130} INFO - 18:00:03
[2022-10-17 11:00:15,182] {dbt_hook.py:130} INFO - 18:00:15  Concurrency: 2 threads (target='dev')
[2022-10-17 11:00:15,182] {dbt_hook.py:130} INFO - 18:00:15
[2022-10-17 11:00:15,189] {dbt_hook.py:130} INFO - 18:00:15  1 of 6 START snapshot DBT_HAMS71.Core_Accounts ................................. [RUN]
[2022-10-17 11:00:15,190] {dbt_hook.py:130} INFO - 18:00:15  2 of 6 START snapshot DBT_HAMS71.Core_Address .................................. [RUN]
[2022-10-17 11:00:44,322] {dbt_hook.py:130} INFO - 18:00:44  2 of 6 ERROR snapshotting DBT_HAMS71.Core_Address .............................. [[31mERROR[0m in 29.13s]
[2022-10-17 11:00:44,323] {dbt_hook.py:130} INFO - 18:00:44  3 of 6 START snapshot DBT_HAMS71.Core_Bank ..................................... [RUN]
[2022-10-17 11:00:49,591] {dbt_hook.py:130} INFO - 18:00:49  1 of 6 OK snapshotted DBT_HAMS71.Core_Accounts ................................. [[32mSUCCESS 1[0m in 34.40s]
[2022-10-17 11:00:49,592] {dbt_hook.py:130} INFO - 18:00:49  4 of 6 START snapshot DBT_HAMS71.Core_Branch ................................... [RUN]
[2022-10-17 11:01:09,563] {dbt_hook.py:130} INFO - 18:01:09  3 of 6 OK snapshotted DBT_HAMS71.Core_Bank ..................................... [[32mSUCCESS 1[0m in 25.24s]
[2022-10-17 11:01:09,564] {dbt_hook.py:130} INFO - 18:01:09  5 of 6 START snapshot DBT_HAMS71.Core_Contact .................................. [RUN]
[2022-10-17 11:01:15,553] {dbt_hook.py:130} INFO - 18:01:15  4 of 6 OK snapshotted DBT_HAMS71.Core_Branch ................................... [[32mSUCCESS 1[0m in 25.96s]
[2022-10-17 11:01:30,112] {dbt_hook.py:130} INFO - 18:01:30  5 of 6 ERROR snapshotting DBT_HAMS71.Core_Contact .............................. [[31mERROR[0m in 20.55s]
[2022-10-17 11:01:30,115] {dbt_hook.py:130} INFO - 18:01:30  6 of 6 SKIP relation DBT_HAMS71.Core_Contact_Account_Branch .................... [[33mSKIP[0m]
[2022-10-17 11:01:30,118] {dbt_hook.py:130} INFO - 18:01:30
[2022-10-17 11:01:30,118] {dbt_hook.py:130} INFO - 18:01:30  Finished running 6 snapshots in 86.27s.
[2022-10-17 11:01:30,130] {dbt_hook.py:130} INFO - 18:01:30
[2022-10-17 11:01:30,130] {dbt_hook.py:130} INFO - 18:01:30  [31mCompleted with 2 errors and 0 warnings:[0m
[2022-10-17 11:01:30,130] {dbt_hook.py:130} INFO - 18:01:30
[2022-10-17 11:01:30,131] {dbt_hook.py:130} INFO - 18:01:30  [33mDatabase Error in snapshot Core_Address (snapshots/Core_Address.sql)[0m
[2022-10-17 11:01:30,131] {dbt_hook.py:130} INFO - 18:01:30    100090 (42P18): Duplicate row detected during DML action
[2022-10-17 11:01:30,131] {dbt_hook.py:130} INFO - 18:01:30    Row Values: ["fb89705ae6d743bf1e848c206e16a1d7", "727", 95, "2660 Summit Alley", "92b3ab239bf5a079b6b0430976403097", 1665696227848000000, 1665696227848000000, NULL]
[2022-10-17 11:01:30,132] {dbt_hook.py:130} INFO - 18:01:30    compiled SQL at target/run/dbt_project/snapshots/Core_Address.sql
[2022-10-17 11:01:30,132] {dbt_hook.py:130} INFO - 18:01:30
[2022-10-17 11:01:30,132] {dbt_hook.py:130} INFO - 18:01:30  [33mDatabase Error in snapshot Core_Contact (snapshots/Core_Contact.sql)[0m
[2022-10-17 11:01:30,133] {dbt_hook.py:130} INFO - 18:01:30    100090 (42P18): Duplicate row detected during DML action
[2022-10-17 11:01:30,133] {dbt_hook.py:130} INFO - 18:01:30    Row Values: ["364a1d85b9e86f5b04f03f2248246b4d", 6077, "Limited Liability", "Fax", "Nader Group", "325", "Administrative Officer", "Genovera Klawi", "Research and Development", "3/20/1961", "83875552", "Married", "3", "43406-0099", "522", "55a7144ac633add4eeb8aef0964876e1", 1665696233044000000, 1665696233044000000, NULL]
[2022-10-17 11:01:30,133] {dbt_hook.py:130} INFO - 18:01:30    compiled SQL at target/run/dbt_project/snapshots/Core_Contact.sql
[2022-10-17 11:01:30,134] {dbt_hook.py:130} INFO - 18:01:30
[2022-10-17 11:01:30,134] {dbt_hook.py:130} INFO - 18:01:30  Done. PASS=3 WARN=0 ERROR=2 SKIP=1 TOTAL=6
[2022-10-17 11:01:31,835] {dbt_hook.py:132} INFO - Command exited with return code 1
[2022-10-17 11:01:31,844] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/airflow/airflow_env/lib/python3.8/site-packages/airflow_dbt/operators/dbt_operator.py", line 126, in execute
    self.create_hook().run_cli('snapshot')
  File "/home/ubuntu/airflow/airflow_env/lib/python3.8/site-packages/airflow_dbt/hooks/dbt_hook.py", line 138, in run_cli
    raise AirflowException("dbt command failed")
airflow.exceptions.AirflowException: dbt command failed
[2022-10-17 11:01:31,848] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dbt, task_id=dbt_snapshot, execution_date=20221013T000400, start_date=20221017T180000, end_date=20221017T180131
[2022-10-17 11:01:31,858] {standard_task_runner.py:92} ERROR - Failed to execute job 113 for task dbt_snapshot (dbt command failed; 261122)
[2022-10-17 11:01:31,884] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-17 11:01:31,909] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
