[2022-10-13 14:21:11,410] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dbt_dag_bash.dbt_run manual__2022-10-13T21:20:44.897252+00:00 [queued]>
[2022-10-13 14:21:11,415] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dbt_dag_bash.dbt_run manual__2022-10-13T21:20:44.897252+00:00 [queued]>
[2022-10-13 14:21:11,415] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-13 14:21:11,416] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-13 14:21:11,416] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-13 14:21:11,426] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): dbt_run> on 2022-10-13 21:20:44.897252+00:00
[2022-10-13 14:21:11,429] {standard_task_runner.py:52} INFO - Started process 250207 to run task
[2022-10-13 14:21:11,433] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_dag_bash', 'dbt_run', 'manual__2022-10-13T21:20:44.897252+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/dbt_bashOperator.py', '--cfg-path', '/tmp/tmpb8bk8nw9', '--error-file', '/tmp/tmpmj4ts_4x']
[2022-10-13 14:21:11,433] {standard_task_runner.py:80} INFO - Job 88: Subtask dbt_run
[2022-10-13 14:21:11,468] {task_command.py:370} INFO - Running <TaskInstance: dbt_dag_bash.dbt_run manual__2022-10-13T21:20:44.897252+00:00 [running]> on host ubuntu
[2022-10-13 14:21:11,506] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dbt_dag_bash
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2022-10-13T21:20:44.897252+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-13T21:20:44.897252+00:00
[2022-10-13 14:21:11,507] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-10-13 14:21:11,508] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'dbt run -m Core']
[2022-10-13 14:21:11,517] {subprocess.py:85} INFO - Output:
[2022-10-13 14:21:14,325] {subprocess.py:92} INFO - 21:21:14  Encountered an error:
[2022-10-13 14:21:14,325] {subprocess.py:92} INFO - Runtime Error
[2022-10-13 14:21:14,325] {subprocess.py:92} INFO -   fatal: Not a dbt project (or any of the parent directories). Missing dbt_project.yml file
[2022-10-13 14:21:14,436] {subprocess.py:96} INFO - Command exited with return code 2
[2022-10-13 14:21:14,447] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/airflow/airflow_env/lib/python3.8/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-10-13 14:21:14,450] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dbt_dag_bash, task_id=dbt_run, execution_date=20221013T212044, start_date=20221013T212111, end_date=20221013T212114
[2022-10-13 14:21:14,460] {standard_task_runner.py:92} ERROR - Failed to execute job 88 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 250207)
[2022-10-13 14:21:14,504] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-13 14:21:14,530] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
