[2022-10-10 04:03:54,212] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dbt.dbt_snapshot manual__2022-10-10T11:03:09.822923+00:00 [queued]>
[2022-10-10 04:03:54,218] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dbt.dbt_snapshot manual__2022-10-10T11:03:09.822923+00:00 [queued]>
[2022-10-10 04:03:54,218] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-10 04:03:54,219] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-10 04:03:54,219] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-10 04:03:54,232] {taskinstance.py:1377} INFO - Executing <Task(DbtSnapshotOperator): dbt_snapshot> on 2022-10-10 11:03:09.822923+00:00
[2022-10-10 04:03:54,235] {standard_task_runner.py:52} INFO - Started process 193253 to run task
[2022-10-10 04:03:54,246] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dbt', 'dbt_snapshot', 'manual__2022-10-10T11:03:09.822923+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/dbt_airflow.py', '--cfg-path', '/tmp/tmpaqeeport', '--error-file', '/tmp/tmpysalm48b']
[2022-10-10 04:03:54,247] {standard_task_runner.py:80} INFO - Job 47: Subtask dbt_snapshot
[2022-10-10 04:03:54,345] {task_command.py:370} INFO - Running <TaskInstance: dbt.dbt_snapshot manual__2022-10-10T11:03:09.822923+00:00 [running]> on host ubuntu
[2022-10-10 04:03:54,441] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dbt
AIRFLOW_CTX_TASK_ID=dbt_snapshot
AIRFLOW_CTX_EXECUTION_DATE=2022-10-10T11:03:09.822923+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-10T11:03:09.822923+00:00
[2022-10-10 04:03:54,442] {dbt_hook.py:117} INFO - dbt snapshot
[2022-10-10 04:03:54,455] {dbt_hook.py:126} INFO - Output:
[2022-10-10 04:03:57,967] {dbt_hook.py:130} INFO - 11:03:57  Running with dbt=1.1.0
[2022-10-10 04:03:58,091] {dbt_hook.py:130} INFO - 11:03:58  Found 6 models, 5 tests, 6 snapshots, 0 analyses, 400 macros, 0 operations, 7 seed files, 2 sources, 0 exposures, 0 metrics
[2022-10-10 04:03:58,096] {dbt_hook.py:130} INFO - 11:03:58
[2022-10-10 04:04:01,640] {dbt_hook.py:130} INFO - 11:04:01  Concurrency: 2 threads (target='dev')
[2022-10-10 04:04:01,641] {dbt_hook.py:130} INFO - 11:04:01
[2022-10-10 04:04:01,648] {dbt_hook.py:130} INFO - 11:04:01  1 of 6 START snapshot DBT_HAMS71.Core_Accounts ................................. [RUN]
[2022-10-10 04:04:01,650] {dbt_hook.py:130} INFO - 11:04:01  2 of 6 START snapshot DBT_HAMS71.Core_Address .................................. [RUN]
[2022-10-10 04:04:07,381] {dbt_hook.py:130} INFO - 11:04:07  2 of 6 ERROR snapshotting DBT_HAMS71.Core_Address .............................. [[31mERROR[0m in 5.73s]
[2022-10-10 04:04:07,383] {dbt_hook.py:130} INFO - 11:04:07  3 of 6 START snapshot DBT_HAMS71.Core_Bank ..................................... [RUN]
[2022-10-10 04:04:07,806] {dbt_hook.py:130} INFO - 11:04:07  1 of 6 OK snapshotted DBT_HAMS71.Core_Accounts ................................. [[32mSUCCESS 1[0m in 6.16s]
[2022-10-10 04:04:07,807] {dbt_hook.py:130} INFO - 11:04:07  4 of 6 START snapshot DBT_HAMS71.Core_Branch ................................... [RUN]
[2022-10-10 04:04:14,122] {dbt_hook.py:130} INFO - 11:04:14  3 of 6 OK snapshotted DBT_HAMS71.Core_Bank ..................................... [[32mSUCCESS 1[0m in 6.74s]
[2022-10-10 04:04:14,123] {dbt_hook.py:130} INFO - 11:04:14  5 of 6 START snapshot DBT_HAMS71.Core_Contact .................................. [RUN]
[2022-10-10 04:04:15,087] {dbt_hook.py:130} INFO - 11:04:15  4 of 6 OK snapshotted DBT_HAMS71.Core_Branch ................................... [[32mSUCCESS 1[0m in 7.28s]
[2022-10-10 04:04:23,261] {dbt_hook.py:130} INFO - 11:04:23  5 of 6 ERROR snapshotting DBT_HAMS71.Core_Contact .............................. [[31mERROR[0m in 9.14s]
[2022-10-10 04:04:23,263] {dbt_hook.py:130} INFO - 11:04:23  6 of 6 SKIP relation DBT_HAMS71.Core_Contact_Account_Branch .................... [[33mSKIP[0m]
[2022-10-10 04:04:23,266] {dbt_hook.py:130} INFO - 11:04:23
[2022-10-10 04:04:23,266] {dbt_hook.py:130} INFO - 11:04:23  Finished running 6 snapshots in 25.17s.
[2022-10-10 04:04:23,280] {dbt_hook.py:130} INFO - 11:04:23
[2022-10-10 04:04:23,280] {dbt_hook.py:130} INFO - 11:04:23  [31mCompleted with 2 errors and 0 warnings:[0m
[2022-10-10 04:04:23,280] {dbt_hook.py:130} INFO - 11:04:23
[2022-10-10 04:04:23,281] {dbt_hook.py:130} INFO - 11:04:23  [33mDatabase Error in snapshot Core_Address (snapshots/Core_Address.sql)[0m
[2022-10-10 04:04:23,281] {dbt_hook.py:130} INFO - 11:04:23    100090 (42P18): Duplicate row detected during DML action
[2022-10-10 04:04:23,281] {dbt_hook.py:130} INFO - 11:04:23    Row Values: ["fb89705ae6d743bf1e848c206e16a1d7", "727", 95, "2660 Summit Alley", "3e786dd248fbf1f0cc2f4087f42b399c", 1665399732220000000, 1665399732220000000, NULL]
[2022-10-10 04:04:23,282] {dbt_hook.py:130} INFO - 11:04:23    compiled SQL at target/run/dbt_project/snapshots/Core_Address.sql
[2022-10-10 04:04:23,282] {dbt_hook.py:130} INFO - 11:04:23
[2022-10-10 04:04:23,282] {dbt_hook.py:130} INFO - 11:04:23  [33mDatabase Error in snapshot Core_Contact (snapshots/Core_Contact.sql)[0m
[2022-10-10 04:04:23,283] {dbt_hook.py:130} INFO - 11:04:23    100090 (42P18): Duplicate row detected during DML action
[2022-10-10 04:04:23,283] {dbt_hook.py:130} INFO - 11:04:23    Row Values: ["364a1d85b9e86f5b04f03f2248246b4d", 6077, "Limited Liability", "Fax", "Nader Group", "325", "Administrative Officer", "Genovera Klawi", "Research and Development", "3/20/1961", "83875552", "Married", "3", "43406-0099", "522", "008c45edee9e64fd1cb14b433798cf5b", 1665399737479000000, 1665399737479000000, NULL]
[2022-10-10 04:04:23,283] {dbt_hook.py:130} INFO - 11:04:23    compiled SQL at target/run/dbt_project/snapshots/Core_Contact.sql
[2022-10-10 04:04:23,284] {dbt_hook.py:130} INFO - 11:04:23
[2022-10-10 04:04:23,284] {dbt_hook.py:130} INFO - 11:04:23  Done. PASS=3 WARN=0 ERROR=2 SKIP=1 TOTAL=6
[2022-10-10 04:04:24,847] {dbt_hook.py:132} INFO - Command exited with return code 1
[2022-10-10 04:04:24,856] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/airflow/airflow_env/lib/python3.8/site-packages/airflow_dbt/operators/dbt_operator.py", line 126, in execute
    self.create_hook().run_cli('snapshot')
  File "/home/ubuntu/airflow/airflow_env/lib/python3.8/site-packages/airflow_dbt/hooks/dbt_hook.py", line 138, in run_cli
    raise AirflowException("dbt command failed")
airflow.exceptions.AirflowException: dbt command failed
[2022-10-10 04:04:24,861] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dbt, task_id=dbt_snapshot, execution_date=20221010T110309, start_date=20221010T110354, end_date=20221010T110424
[2022-10-10 04:04:24,872] {standard_task_runner.py:92} ERROR - Failed to execute job 47 for task dbt_snapshot (dbt command failed; 193253)
[2022-10-10 04:04:24,900] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-10 04:04:24,918] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
